(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e,f="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var l={o:!0},m={};try{m.__proto__=l;h=m.o;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=g,p=this||self,q=function(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a};var r=function(a,b,d){d=void 0===d?null:d;var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,d);b.dispatchEvent(c);return c};var t=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,t);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};q(t,Error);t.prototype.name="CustomError";var u=function(a,b){a=a.split("%s");for(var d="",c=a.length-1,k=0;k<c;k++)d+=a[k]+(k<b.length?b[k]:"%s");t.call(this,d+a[c])};q(u,t);u.prototype.name="AssertionError";var v=function(a,b,d){if(!a){var c="Assertion failed";if(b){c+=": "+b;var k=Array.prototype.slice.call(arguments,2)}throw new u(""+c,k||[]);}return a},w=function(a,b){throw new u("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var y=function(a,b){this.f=b===x?a:""};y.prototype.A=!0;y.prototype.v=function(){return this.f.toString()};y.prototype.toString=function(){return"SafeUrl{"+this.f+"}"};var z=function(a){if(a instanceof y&&a.constructor===y)return a.f;var b=typeof a;w("expected object of type SafeUrl, got '"+a+"' of type "+("object"!=b?b:a?Array.isArray(a)?"array":b:"null"));return"type_error:SafeUrl"},A=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,x={};var B=[],C=function(a){a=B.indexOf(a);0<=a&&B.splice(a,1)};document.addEventListener("click",function(a){for(var b=0;b<B.length;b++)if(25>Math.abs(a.clientX-B[b].s)&&25>Math.abs(a.clientY-B[b].u)||25>Math.abs(a.screenX-B[b].G)&&25>Math.abs(a.screenY-B[b].H))B.splice(b,1),a.stopPropagation(),a.preventDefault()},!0);var D=function(){var a=HTMLElement.call(this)||this;a.l=0;a.m=0;a.c=null;a.h=null;a.b=null;a.g=null;a.i=a.B.bind(a);a.a=!0;return a},E=HTMLElement;D.prototype=f(E.prototype);
D.prototype.constructor=D;if(n)n(D,E);else for(var F in E)if("prototype"!=F)if(Object.defineProperties){var G=Object.getOwnPropertyDescriptor(E,F);G&&Object.defineProperty(D,F,G)}else D[F]=E[F];e=D.prototype;e.connectedCallback=function(){this.b||(this.c=this.j.bind(this),this.h=this.F.bind(this),this.b=this.D.bind(this),this.g=this.C.bind(this));this.addEventListener("click",this.c,!1);this.addEventListener("touchstart",this.h,!1);this.addEventListener("action",this.i,!1)};
e.disconnectedCallback=function(){this.removeEventListener("click",this.c,!1);this.removeEventListener("touchstart",this.h,!1);this.removeEventListener("action",this.i,!1)};e.j=function(a){this.a&&r("action",this,a);this.a=!0};e.F=function(a){this.addEventListener("touchmove",this.b,!1);this.addEventListener("touchend",this.g,!1);a=a.touches[0];this.l=a.clientX;this.m=a.clientY};
e.C=function(a){this.j(a);this.removeEventListener("touchmove",this.b,!1);this.removeEventListener("touchend",this.g,!1);a=a.changedTouches[0];a={s:a.clientX,u:a.clientY,G:a.screenX,H:a.screenY};B.push(a);setTimeout(C.bind(null,a),2500)};e.D=function(a){a=a.touches[0];this.a=this.a&&10>=Math.abs(this.l-a.clientX)&&10>=Math.abs(this.m-a.clientY)};
e.B=function(a){var b=this.getAttribute("exit-id"),d=this.getAttribute("product-index"),c=this.getAttribute("exit-override-url");c&&!r("tapareaexit",this,{"exit-id":b,url:c,"product-index":d,"action-event":a.detail}).detail.handled&&(c instanceof y?a=c:(a=c,a instanceof y||(a="object"==typeof a&&a.A?a.v():String(a),v(A.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new y(a,x))),p.open(z(a),"",void 0,void 0))};customElements.define("gwd-taparea",D);}).call(this);
